# .gitpod.yml na raiz do seu projeto Spring Boot
# Use uma imagem Linux/Ubuntu genérica
image: gitpod/workspace-full-vnc # Ou gitpod/workspace-full, ou gitpod/workspace-ubuntu-latest

tasks:
  - name: Install Java and Maven
    init: |
      # Instala o OpenJDK 21
      sudo apt-get update && sudo apt-get install -y openjdk-21-jdk
      # Adiciona o JAVA_HOME para a sessão
      echo 'export JAVA_HOME="/usr/lib/jvm/java-21-openjdk-amd64"' >> ~/.bashrc
      echo 'export PATH="$JAVA_HOME/bin:$PATH"' >> ~/.bashrc
      # Instala o Maven (se não vier com a imagem)
      sudo apt-get install -y maven
      # Garante que as variáveis de ambiente sejam carregadas para a tarefa seguinte
      source ~/.bashrc
      # Roda o Maven install para construir o projeto (se for Maven)
      mvn clean install
    command: |
      # Garante que as variáveis de ambiente sejam carregadas para rodar o app
      source ~/.bashrc
      mvn spring-boot:run

ports:
  - port: 8080
    onOpen: open-browser # Abre diretamente no navegador, ou open-preview se preferir a janela interna